inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - "config/environments/*"
    - "vender/**/*"
    - "bin/**"
    - "db/**/*"
    - "tmp/**/*"
    - "lib/**/*"
    - "Gemfile"
    - "node_modules/node-sass/src/**/*"
    - "config/unicorn.conf.rb"

Style/HashEachMethods:   
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/AsciiComments:
  Enabled: false
